
[functions.google-calendar-auth]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.gpt-processor]
verify_jwt = true

[functions.check-availability]
verify_jwt = true

[functions.create-appointment]
verify_jwt = true

[functions.cancel-appointment]
verify_jwt = true

[functions.reschedule-appointment]
verify_jwt = true

[functions.whatsapp-test-message]
verify_jwt = false

[functions.openai-test]
verify_jwt = false

[functions.appointment-assistant]
verify_jwt = true

[functions.calcom-integration]
enabled = true
verify_jwt = true
import_map = "./functions/calcom-integration/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/calcom-integration/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/calcom-integration/*.html" ]

[functions.storage-upload]
enabled = true
verify_jwt = true
import_map = "./functions/storage-upload/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/storage-upload/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/storage-upload/*.html" ]
