
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Try to get environment variables, with fallbacks for development
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL || 'https://gusvinsszquyhppemkgq.supabase.co';
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1c3ZpbnNzenF1eWhwcGVta2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTE1NzgsImV4cCI6MjA2MTMyNzU3OH0.eueTAv2AG1hCyF8TXdtZ6KSGbHp4BpQJasSFYxz3zKc';

// For backward compatibility - import this client using:
// import { supabase } from "@/integrations/supabase/client";
// But consider updating to the browser client instead:
// import { supabaseBrowser } from "@/integrations/supabase/browserClient";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);
