// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gusvinsszquyhppemkgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd1c3ZpbnNzenF1eWhwcGVta2dxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3NTE1NzgsImV4cCI6MjA2MTMyNzU3OH0.eueTAv2AG1hCyF8TXdtZ6KSGbHp4BpQJasSFYxz3zKc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);